services:
  php:
    build: ./docker/php
    container_name: event-sourcing-php
    volumes:
      - .:/app
    working_dir: /app
    command: "tail -f /dev/null"
    depends_on:
      - mysql
      - redis
    networks:
      - phpnet

  mysql:
    image: mysql:latest
    container_name: event-sourcing-mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: changeme
    ports:
      - "3306:3306"
    networks:
      - phpnet

  redis:
    image: redis:latest
    container_name: event-sourcing-redis
    ports:
      - "6379:6379"
    networks:
      - phpnet

networks:
  phpnet:
    driver: bridge
